### ISSUE TITLE
Create `requirements.txt`

### ISSUE THREAD

**Issue by jartis** [JacksonParodi/rpgolf#1]
A common practice is to list any packages required by a project in a file named `requirements.txt`. In your case, the contents of this file would just be:

```
pygame
opensimplex
```

That way, someone who snags the repo can run the command:

`pip install -r requirements.txt`

and get everything necessary to run the game.

**Comment by JacksonParodi** [comment]
thanks, just made it for [c6a5441](https://github.com/JacksonParodi/rpgolf/commit/c6a54418437f778c2f1c13b7d3435548d0fa4905)
